# Generated by Django 5.1.4 on 2024-12-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveIntegerField()),
                ('electricityCharges', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('roomAccomodation', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('commonRoom', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('studyRoom', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('WiFi', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dept_id', models.IntegerField()),
                ('degreeDuration', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='HostelStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_role', models.CharField(max_length=100)),
                ('staff_contact', models.CharField(max_length=11)),
                ('staff_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('breakfast', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10)),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=10)),
                ('noOfStudents', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('st_contactNumber', models.CharField(max_length=11)),
                ('st_email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(max_length=11)),
                ('dept_name', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocationStatus', models.CharField(choices=[('allocated', 'Allocated'), ('unallocated', 'Unallocated')], max_length=20)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.room')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyMealConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('daysConsumed', models.PositiveIntegerField()),
                ('perDayCharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDuesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=7)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualDuesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveIntegerField()),
                ('pais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualChallan',
            fields=[
                ('challan_no', models.AutoField(primary_key=True, serialize=False)),
                ('validUpto', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.room')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitorName', models.CharField(max_length=255)),
                ('purposeOfVisit', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('dateOfVisit', models.DateField()),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelManagement.student')),
            ],
        ),
    ]
