# Generated by Django 5.1.4 on 2024-12-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept_name',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('SE', 'Software Engineering'), ('PharmD', 'D Pharmacy')], max_length=6),
        ),
    ]
