# Generated by Django 5.1.4 on 2025-01-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0002_alter_student_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelManagement.room'),
        ),
    ]
