# Generated by Django 5.1.4 on 2025-01-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0005_remove_annualduesstatus_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymealconsumption',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
    ]
