# Generated by Django 5.1.4 on 2025-01-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0006_alter_monthlymealconsumption_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymealconsumption',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
