# Generated by Django 5.1.4 on 2025-01-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0006_alter_monthlyduesstatus_month_and_more'),
        ('hostelManagement', '0011_alter_monthlymealconsumption_month_and_more'),
    ]

    operations = [
    ]
