# Generated by Django 5.1.4 on 2025-01-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelManagement', '0012_merge_20250101_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyduesstatus',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='October', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyduesstatus',
            name='year',
            field=models.PositiveIntegerField(default='2024'),
        ),
    ]
